---
- name: Install and run Node.js application
  hosts: all
  tasks:
    - name: Clone repository
      git:
        repo: https://github.com/DavidHiuhu/your_node_app.git
        dest: /path/to/clone
        version: master

    - name: Install dependencies
      npm:
        path: /path/to/clone

    - name: Start the application
      command: node /path/to/clone/app.js
      async: 30
      poll: 0
